name: dii_ms
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - ase
  - dscribe
  - ipykernel
  - notebook
  - scipy
  - seaborn
  - pandas
  - scikit-image
  - pip
  - pip:
    - dadapy==0.3.2
